#
# Makefile
#

include ../Makedefs
include ../Makerules

all:
	$(MAKE) -C $(ARCHDIR) all

install:
	$(MAKE) -C $(ARCHDIR) install

clean:
	$(MAKE) -C $(ARCHDIR) clean

clobber: clean
	$(MAKE) -C $(ARCHDIR) clobber
